name: Push Branch

on:
  push:
    branches:
      - '*'

env: {}

jobs:
  call-build:
    uses: ./.github/workflows/build.yaml
    with:
      project_name: i343-native-static-library
    secrets: inherit
