name: Push Release Tag

on:
  push:
    tags:
      - 'v*'

env: {}

jobs:
  call-build:
    uses: ./.github/workflows/build.yaml
    with:
      project_name: i343-native-static-library
    secrets: inherit
  publish:
    name: Publish
    runs-on: windows-2022
    needs:
      - call-build
    steps:
      - name: Download NuGet Artifact
        uses: actions/download-artifact@v3
        with:
          name: NuGet
      - name: Configure GitHub Packages
        run: nuget sources add -Name GitHub -UserName v-kentro -Password ${{ secrets.GITHUB_TOKEN }} -Source https://nuget.pkg.github.com/v-kentro/index.json -NonInteractive
      - name: Upload NuGet Package
        run: nuget push *.nupkg -ApiKey ${{ secrets.GITHUB_TOKEN }} -Source GitHub -NonInteractive
